apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnyt-be
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnyt-be
  template:
    metadata:
      labels:
        app: mnyt-be
    spec:
      containers:
      - name: mnyt-be
        image: ghcr.io/tears-inrain/mnyt-be:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__DefaultConnection
          value: "Server=172.25.192.1;uid=sa;pwd=12345;Database=PrenatalCareDB;TrustServerCertificate=true;Encrypt=true;"
        - name: Authentication__Jwt__Secret
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: Authentication__Jwt__Secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: JWT_SECRET
        - name: JWT_ISSUER
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: JWT_ISSUER
        - name: JWT_AUDIENCE
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: JWT_AUDIENCE
      imagePullSecrets:
      - name: ghcr-secret