apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: default
type: Opaque
stringData:
  JWT_SECRET: xsgjI3fYTWmcxfsFSXQwjnv8UxkUKH1A92QT
  JWT_ISSUER: mnyt-be
  JWT_AUDIENCE: mnyt-be
  Authentication__Jwt__Secret: xsgjI3fYTWmcxfsFSXQwjnv8UxkUKH1A92QT